spring:
  datasource:
    url: jdbc:h2:mem://localhost:5432/ayventory
    username: sa
    password: pass
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
